# Number of days of inactivity before an issue becomes stale 
daysUntilStale: false

# Number of days of inactivity before a stale issue is closed 
daysUntilClose: false

# Issues with these labels will never be considered stale
exemptLabels:
  - pinned

# Label to use when marking an issue as stale
staleLabel: stale

# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  Thank you for your contributions.

  This issue has not had any activity in last ~6 months! 
  Due to this we are marking this issue as stale because of that lack of activity.
  If this issue is still actively occuring, please comment and we will re-label.

# Comment to post when closing a stale issue. Set to `false` to disable
#closeComment: >
#  This issue has been closed as there have not been any other updates since my last update on the issue.
#  If this is an issue which is still valid, feel free to reopen it.
