AllCops:
  TargetRubyVersion: 3.2
  NewCops: disable
  Include:
    - '**/*.lic'
    - '**/*.rb'

Naming/FileName:
  Enabled: false
  
Naming/AccessorMethodName:
   Enabled: false

Naming/PredicateName:
  Enabled: false

Style:
  Enabled: false

Layout/HashAlignment:
  EnforcedHashRocketStyle: table

Layout/EndOfLine:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false
