---
# See https://github.com/rpherbig/dr-scripts/wiki/YAML-Settings for documentation


hometown: Crossing

# Combat settings
aim_fillers:
  Crossbow:
  - bob
  - bob
  Bow:
  - bob
  - bob
  - bob
  Slings:
  - bob
  - bob
  - bob
stances:
  Bow:
  - Evasion
  - Shield Usage
  - Parry Ability
  Crossbow:
  - Evasion
  - Shield Usage
  - Parry Ability
  Slings:
  - Evasion
  - Shield Usage
  - Parry Ability
  Offhand Weapon:
  - Evasion
  - Shield Usage
  - Parry Ability
stance_override:
skinning:
  skin: true
  arrange_all: false
  arrange_count: 0
  tie_bundle: false
charged_maneuvers:
  Brawling: palmstrike
  Bow: powershot
  Crossbow: powershot
  Slings: powershot
  Small Edged: cleave
  Large Edged: cleave
  Twohanded Edged: rush
  Small Blunt: crash
  Large Blunt: crash
  Twohanded Blunt: crash
  Staves: twirl
  Polearms: impale
dance_threshold: 0
dance_skill: Small Edged
dance_actions:
- analyze
- circle
- bob
- weave
manipulate_threshold:
training_abilities:
  Hunt: 80
fatigue_regen_threshold: 90
fatigue_regen_action: bob
summoned_weapons:
summoned_weapons_element:
summoned_weapons_ingot:
buff_spells:
offensive_spells:
offensive_spell_cycle:
aim_fillers_stealth:
buff_nonspells:
dance_actions_stealth:
thanatology:
necromancer_healing:
weapon_training:
combat_trainer_target_increment: 3
combat_trainer_action_count: 10
dual_load: false
use_stealth_attacks: false
stealth_attack_aimed_action: poach
backstab:
ambush: false
performance_monitor_weapons:
retreat_threshold:
use_weak_attacks: false
loot_bodies: true
dump_junk: false
analyze_combo_type:
offensive_spell_mana_threshold: 40
training_spell_mana_threshold: 50
buff_spell_mana_threshold: 40




# Hunting settings
training_manager_hunting_priority: false
training_manager_priority_skills:
hunting_info:




stun_weapon:
stun_weapon_skill:
stun_skill: Debilitation

# Repair settings
repair_withdrawal_amount: 10_000





# Safe-room settings
safe_room_id:
safe_room_take:
safe_room_give:
safe_room_tip_threshold:
safe_room_tip_amount:
safe_room_empath:





# Spellcasting (and Khri) settings
cambrinth: armband
cambrinth_cap: 32
stored_cambrinth: false
prep_scaling_factor: 0.98
kneel_khri: false




# Looting settings
loot_additions:
loot_subtractions:
loot_specials:




# Non-combat settings
exp_timers:
  Stealth: 300
  First Aid: 400
  Locksmithing: 600
  Theurgy: 720
  Thievery: 600
  Attunement: 130
listen: false
safe_room: 851
hide_to_steal: true
bin_stolen: false
stealing_bag: backpack
hand_armor: gloves
exit_on_skills_capped: false
crossing_training_sorcery:
crossing_training_sorcery_room: 1137
crossing_training_requires_movement:
- Alchemy
- Appraisal
- Athletics
- Attunement
- Empathy
- Engineering
- Forging
- Outfitting
- Scouting
- Sorcery
- Stealth
- Thievery
- Theurgy
- Trading
forage_item:
braid_item:
training_spells:
cyclic_training_spells:
cyclic_cycle_skills:
train_with_spells: true
training_nonspells:
crossing_training:
use_research: false
research_skills:
water_holder:
flint_lighter:
astrology_buffs:
scouting_buffs:
crossing_training_stationary_skills_only: false
outdoor_room: 793
textbook: false
textbook_type: textbook
dedicated_camb_use:





# Crafting settings
crafting_container: backpack
forging_tools:
- diagonal-peen hammer
- tong
- bellow
- shovel
knitting_tools:
- knitting needle
shaping_tools:
- carving knife
- shaper
- drawknife
- rasp
alchemy_tools:
- mortar
- pestle
- bowl
- mixing stick
- sieve
carving_tools:
- chisels
- rifflers
- rasp
work_order_disciplines:
train_workorders:
forge_container: backpack
forging_belt:
engineering_belt:
outfitting_belt:
alchemy_belt:
mark_crafted_goods: false




forests_to_chop:
- neg_to_kaerna
- cougars
lumber_skip_populated: true
lumber_buddy_chop_every_room: false
lumber_buddy_tree_list:
# MISC
#- Durian
# common
# - Ash #shortbows
# - Birch #composite
# - Maple #longbows
# - Oak #martial
# rare
- Cherry #shortbows
- Ramin #longbows
- Hickory #Composite
- Lelori #Composite
- Sandalwood #Composite
#- Ironwood #martial
# very rare
- Bloodwood
- Copperwood
- Mistwood
- Goldwood
- Azurelle
- Silverwood

lumber_implement: axe
lumber_use_packet: true
lumber_while_training: false

# Mining settings
mines_to_mine:
- wicked_burrow
- stone_clan
- waterfall
mining_skip_populated: true
mining_buddy_mine_every_room: false
mining_buddy_vein_list:
# uncommon
- Silver
# rare
- Gold
- Platinum
- Lumium
- Niniam
- Electrum
- Muracite
- Darkstone
# very rare
- Damite
- Kertig
- Haralun
- Glaes
- Animite

mining_ignored_stone_sizes:
- pebble

mining_implement: shovel
mine_use_packet: true
mine_while_training: false





# Lockpicking settings
stop_pick_on_mindlock: true
use_lockpick_ring: true
lockpick_container: ring
lockpick_type: ordinary
harvest_traps: true
picking_box_source: duffel bag
picking_box_storage: backpack
picking_pet_box_source:
lockpick_dismantle:
lockpick_buffs:
lockpick_room_id:
lockpick_ignore_difficulty: false






# Sell loot settings
sell_loot_pouch: true
sell_loot_bundle: true
sell_loot_money_on_hand: 3 silver
sell_pouches_for_trading: false
sale_pouches_container: backpack

# Misc settings
storage_containers:
gear:
gear_sets:
empath_healing:

osrel_no_harness: false
osrel_amount:

spare_gem_pouch_container:
gem_pouch_adjective:

workorder_diff: challenging
trail_override:
ignored_npcs:

favor_god: Hodierna
immortal_aspect:
favor_goal:
hunting_buddies:
have_telescope: false
theurgy_supply_container: backpack

stealing_high_acceptable_count: 1
stealing_low_acceptable_count: 2
steal_past_mindlock: false
stealing_buffs:
npc_stealing_attempt_count: 0

writing_instrument:
dont_stalk: false

stop_hunting_if_bleeding: true
engineering_room:
alchemy_room:

tithe: false

cleaning_cloth: chamois cloth
cast_only_to_train: false
priority_defense:
tk_ammo:

listen_skills:
- Large Edged
- Twohanded Edged
- Small Blunt
- Light Thrown
- Brawling
- Offhand Weapon
- Melee Mastery
- Missile Mastery
- Life Magic
- Attunement
- Arcana
- Augmentation
- Utility
- Warding
- Athletics
- Perception
- First Aid
- Outdoorsmanship
- Scholarship
- Mechanical Lore
- Appraisal
- Performance
- Tactics
- Stealth
- Bow
- Evasion
- Parry Ability
- Small Edged
- Defending
- Light Armor
- Chain Armor
- Shield Usage
- Targeted Magic
- Debilitation
- Brigandine
- Plate Armor
- Large Blunt
- Twohanded Blunt
- Slings
- Crossbow
- Staves
- Polearms
- Heavy Thrown
- Locksmithing
- Skinning
- Forging
- Engineering
- Outfitting
- Alchemy

dont_steal_list:
waggle_sets:
mine_for_outdoorsmanship: false

health_threshold: 50
depart_on_death: false

lichbot_buffs:
lichbot_compost: false
custom_loot_type:

lockpick_buff_bot:
symbiosis_learning_threshold: 2

quit_on_status_warning: false

compost_room: 991

carving_workorder_material_type: stone

slack_username:
workorder_min_items: 2
workorder_max_items: 3
workorder_recipes:

darkbox_junk:
- sharkskin
- root
- rockweed
- kelp
- flowers
- apple
- strawberry
- root
- snake
- cobra
- coin
darkbox_stop_on_wounded: false

pumpkin_junk:
- socks
- seeds
- muffin
- pumpkins
- shoe
- line
- ribbon
- necklace
- mask
- net
- cuff
- earcuff
- handker
- nose-stud
- pin
- armband
- wristlet
- necklace
- bracelet
- charm
- gold ring
- garter
- carving knife
- skeletons
- wormwood ring
- earrings
- steel ring
- scarf
- mug
- bracer
- copper button
- torque
- fuzzy bats
- blown-glass pumpkin
- plush maggot
- bandana
- gloves
- zombies
- jellybeans
- doll
- ghosts
- silver wristcuff
- cambrinth orb
- platinum ring

empty_hunting_room_messages:
- Anyone here?
