name: Rubocop
on:
  push:
    branches: 
      - 'main'
    paths:
      - "*.lic"
      - "*.rb"
  pull_request:
    paths:
      - "*.lic"
      - "*.rb"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rubocop:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.3']
    name: Run Rubocop on Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Rubocop
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            bundle exec rubocop ${file}
          done
