name: Valid Ruby syntax

on:
  push:
    branches: 
      - 'main'
    paths:
      - "*.lic"
      - "*.rb"
  pull_request:
    paths:
      - "*.lic"
      - "*.rb"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_syntax:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.3']
    name: Run tests on Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: step-security/changed-files@3dbe17c78367e7d60f00d78ae6781a35be47b4a1
        with:
          files: |
            *.lic
            *.rb
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run Ruby syntax check on changed scripts
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            ruby -c ${file}
          done
